services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    # ãƒ›ã‚¹ãƒˆOS (WSL2ã‹ã‚‰ã®ã‚¢ã‚¯ã‚»ã‚¹) ã«ãƒãƒ¼ãƒˆã‚’å…¬é–‹ã™ã‚‹å¿…è¦ãŒã‚ã‚‹ ğŸ‘ˆ
    ports:
      - '5432:5432'